name: SP500-correction-PE
channels:
- conda-forge
- defaults
dependencies:
- pandas
- scikit-learn
- numpy
- xgboost
- dateparser
- lxml
- matplotlib
- pip:
  - plotly-express
  - fredapi
